services:
  - type: web
    name: protocolr2-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://r2:H425iN91es9wnXG0n787h886CsjMm5gr@dpg-d1mlj0u3jp1c73dqtn7g-a.oregon-postgres.render.com/dbr2"
      - key: DEFAULT_LANGUAGE
        value: "es"
      - key: SUPPORTED_LANGUAGES
        value: "es,en"
      - key: BACKEND_URL
        value: "https://backend-4vzk.onrender.com"
      - key: TELEGRAM_TOKEN
        sync: false
